import type {
  Child,
  AttendanceRecord,
  ScheduleItem,
  Notice,
  ObservationLog,
  DashboardStats,
  ActivityTimeline,
  MealPlan,
} from '../types';

// ── 아이 목록 ──
export const MOCK_CHILDREN: Child[] = [
  {
    id: 'c1',
    name: '김민준',
    age: 5,
    classId: 'class-sunshine',
    className: '해바라기반',
    profileEmoji: '👦',
    birthDate: '2021-03-15',
    parentId: 'p1',
    parentName: '김영희',
    parentPhone: '010-1234-5678',
    allergies: ['우유'],
    notes: '낮잠 시간에 잠을 잘 못 잠',
    gender: 'male',
    traits: [], // 👈 추가
    medicationRequest: null,
  },
  {
    id: 'c2',
    name: '이서아',
    age: 5,
    classId: 'class-sunshine',
    className: '해바라기반',
    profileEmoji: '👧',
    birthDate: '2021-06-22',
    parentId: 'p2',
    parentName: '이정수',
    parentPhone: '010-2345-6789',
    allergies: ['땅콩', '갑각류'],
    notes: '',
    gender: 'female',
    traits: [], // 👈 추가
    medicationRequest: null,
  },
  {
    id: 'c3',
    name: '박지호',
    age: 5,
    classId: 'class-sunshine',
    className: '해바라기반',
    profileEmoji: '👦',
    birthDate: '2021-01-08',
    parentId: 'p3',
    parentName: '박미영',
    parentPhone: '010-3456-7890',
    allergies: [],
    notes: '블록 놀이를 좋아함',
    gender: 'male',
    traits: [], // 👈 추가
    medicationRequest: null,
  },
  {
    id: 'c4',
    name: '최하은',
    age: 5,
    classId: 'class-sunshine',
    className: '해바라기반',
    profileEmoji: '👧',
    birthDate: '2021-08-30',
    parentId: 'p4',
    parentName: '최수진',
    parentPhone: '010-4567-8901',
    allergies: ['계란'],
    notes: '그림 그리기를 좋아함',
    gender: 'female',
    traits: [], // 👈 추가
    medicationRequest: null,
  },
  {
    id: 'c5',
    name: '정예준',
    age: 5,
    classId: 'class-sunshine',
    className: '해바라기반',
    profileEmoji: '👦',
    birthDate: '2021-04-12',
    parentId: 'p5',
    parentName: '정민호',
    parentPhone: '010-5678-9012',
    allergies: [],
    notes: '야외 활동을 즐김',
    gender: 'male',
    traits: [], // 👈 추가
    medicationRequest: null,
  },
  {
    id: 'c6',
    name: '윤서윤',
    age: 5,
    classId: 'class-sunshine',
    className: '해바라기반',
    profileEmoji: '👧',
    birthDate: '2021-11-05',
    parentId: 'p6',
    parentName: '윤지현',
    parentPhone: '010-6789-0123',
    allergies: [],
    notes: '',
    gender: 'female',
    traits: [], // 👈 추가
    medicationRequest: null,
  },
  {
    id: 'c7',
    name: '한도윤',
    age: 5,
    classId: 'class-sunshine',
    className: '해바라기반',
    profileEmoji: '👦',
    birthDate: '2021-07-19',
    parentId: 'p7',
    parentName: '한소정',
    parentPhone: '010-7890-1234',
    allergies: ['밀가루'],
    notes: '음악 활동에 적극적',
    gender: 'male',
    traits: [], // 👈 추가
    medicationRequest: null,
  },
  {
    id: 'c8',
    name: '강하린',
    age: 5,
    classId: 'class-sunshine',
    className: '해바라기반',
    profileEmoji: '👧',
    birthDate: '2021-02-14',
    parentId: 'p8',
    parentName: '강현우',
    parentPhone: '010-8901-2345',
    allergies: [],
    notes: '독서를 좋아함',
    gender: 'female',
    traits: [], // 👈 추가
    medicationRequest: null,
  },
  {
    id: 'c9',
    name: '조시우',
    age: 5,
    classId: 'class-sunshine',
    className: '해바라기반',
    profileEmoji: '👦',
    birthDate: '2021-09-25',
    parentId: 'p9',
    parentName: '조은비',
    parentPhone: '010-9012-3456',
    allergies: [],
    notes: '',
    gender: 'male',
    traits: [], // 👈 추가
    medicationRequest: null,
  },
  {
    id: 'c10',
    name: '임수아',
    age: 5,
    classId: 'class-sunshine',
    className: '해바라기반',
    profileEmoji: '👧',
    birthDate: '2021-05-03',
    parentId: 'p10',
    parentName: '임서연',
    parentPhone: '010-0123-4567',
    allergies: ['대두'],
    notes: '춤추기를 좋아함',
    gender: 'female',
    traits: [], // 👈 추가
    medicationRequest: null,
  },
  {
    id: 'c11',
    name: '장건우',
    age: 5,
    classId: 'class-sunshine',
    className: '해바라기반',
    profileEmoji: '👦',
    birthDate: '2021-10-17',
    parentId: 'p11',
    parentName: '장혜진',
    parentPhone: '010-1111-2222',
    allergies: [],
    notes: '',
    gender: 'male',
    traits: [],
    medicationRequest: null,
  },
  {
    id: 'c12',
    name: '오유진',
    age: 5,
    classId: 'class-sunshine',
    className: '해바라기반',
    profileEmoji: '👧',
    birthDate: '2021-12-01',
    parentId: 'p12',
    parentName: '오지영',
    parentPhone: '010-2222-3333',
    allergies: [],
    notes: '소꿉놀이를 좋아함',
    gender: 'female',
    traits: [],
    medicationRequest: null,
  },
  {
    id: 'c13',
    name: '서지안',
    age: 5,
    classId: 'class-sunshine',
    className: '해바라기반',
    profileEmoji: '👦',
    birthDate: '2021-06-08',
    parentId: 'p13',
    parentName: '서윤아',
    parentPhone: '010-3333-4444',
    allergies: [],
    notes: '',
    gender: 'male',
    traits: [],
    medicationRequest: null,
  },
  {
    id: 'c14',
    name: '권나윤',
    age: 5,
    classId: 'class-sunshine',
    className: '해바라기반',
    profileEmoji: '👧',
    birthDate: '2021-03-27',
    parentId: 'p14',
    parentName: '권민재',
    parentPhone: '010-4444-5555',
    allergies: [],
    notes: '친구들과 잘 어울림',
    gender: 'female',
    traits: [],
    medicationRequest: null,
  },
  {
    id: 'c15',
    name: '황이준',
    age: 5,
    classId: 'class-sunshine',
    className: '해바라기반',
    profileEmoji: '👦',
    birthDate: '2021-08-11',
    parentId: 'p15',
    parentName: '황수민',
    parentPhone: '010-5555-6666',
    allergies: [],
    notes: '',
    gender: 'male',
    traits: [],
    medicationRequest: null,
  },
  {
    id: 'c16',
    name: '안채원',
    age: 5,
    classId: 'class-sunshine',
    className: '해바라기반',
    profileEmoji: '👧',
    birthDate: '2021-01-20',
    parentId: 'p16',
    parentName: '안지수',
    parentPhone: '010-6666-7777',
    allergies: ['새우'],
    notes: '',
    gender: 'female',
    traits: [],
    medicationRequest: null,
  },
  {
    id: 'c17',
    name: '배준서',
    age: 5,
    classId: 'class-sunshine',
    className: '해바라기반',
    profileEmoji: '👦',
    birthDate: '2021-04-05',
    parentId: 'p17',
    parentName: '배은지',
    parentPhone: '010-7777-8888',
    allergies: [],
    notes: '과학 탐구 활동을 좋아함',
    gender: 'male',
    traits: [],
    medicationRequest: null,
  },
  {
    id: 'c18',
    name: '류소율',
    age: 5,
    classId: 'class-sunshine',
    className: '해바라기반',
    profileEmoji: '👧',
    birthDate: '2021-07-14',
    parentId: 'p18',
    parentName: '류지훈',
    parentPhone: '010-8888-9999',
    allergies: [],
    notes: '',
    gender: 'female',
    traits: [],
    medicationRequest: null,
  },
  {
    id: 'c19',
    name: '곽태민',
    age: 5,
    classId: 'class-sunshine',
    className: '해바라기반',
    profileEmoji: '👦',
    birthDate: '2021-11-28',
    parentId: 'p19',
    parentName: '곽미선',
    parentPhone: '010-9999-0000',
    allergies: [],
    notes: '',
    gender: 'male',
    traits: [],
    medicationRequest: null,
  },
  {
    id: 'c20',
    name: '문서영',
    age: 5,
    classId: 'class-sunshine',
    className: '해바라기반',
    profileEmoji: '👧',
    birthDate: '2021-09-09',
    parentId: 'p20',
    parentName: '문혜원',
    parentPhone: '010-1010-2020',
    allergies: [],
    notes: '역할놀이를 즐김',
    gender: 'female',
    traits: [],
    medicationRequest: null,
  },
];

// ── 출석 기록 ──
export const MOCK_ATTENDANCE: AttendanceRecord[] = MOCK_CHILDREN.map((child, i) => ({
  id: `att-${child.id}`,
  childId: child.id,
  date: '2026-04-07',
  status: i < 18 ? ('present' as const) : ('absent' as const),
  arrivalTime: i < 18 ? `09:${String(5 + i * 3).padStart(2, '0')}` : undefined,
  reason: i === 18 ? '체험학습' : i === 19 ? '병결' : undefined,
}));

// ── 일정 ──
export const MOCK_SCHEDULES: ScheduleItem[] = [
  {
    id: 's1',
    title: '등원 및 자유놀이',
    startTime: '09:00',
    endTime: '09:30',
    date: '2026-04-07',
    description: '등원 맞이 및 자유 놀이시간',
    color: '#3b82f6',
    isCompleted: true,
  },
  {
    id: 's2',
    title: '오전 간식 및 자유놀이',
    startTime: '09:30',
    endTime: '10:30',
    date: '2026-04-07',
    description: '오전 간식 배식 후 자유놀이',
    color: '#10b981',
    isCompleted: true,
  },
  {
    id: 's3',
    title: '야외 활동 (숲 체험)',
    startTime: '11:00',
    endTime: '12:00',
    date: '2026-04-07',
    description: '원내 숲 체험 활동',
    color: '#f59e0b',
    isCompleted: false,
  },
  {
    id: 's4',
    title: '점심 식사',
    startTime: '12:00',
    endTime: '13:00',
    date: '2026-04-07',
    description: '점심 식사 및 양치',
    color: '#ef4444',
    isCompleted: false,
  },
  {
    id: 's5',
    title: '낮잠 및 휴식',
    startTime: '13:00',
    endTime: '14:30',
    date: '2026-04-07',
    description: '낮잠 시간',
    color: '#8b5cf6',
    isCompleted: false,
  },
  {
    id: 's6',
    title: '오후 간식',
    startTime: '14:30',
    endTime: '15:00',
    date: '2026-04-07',
    description: '오후 간식 배식',
    color: '#ec4899',
    isCompleted: false,
  },
  {
    id: 's7',
    title: '특별 활동 (음악)',
    startTime: '15:00',
    endTime: '16:00',
    date: '2026-04-07',
    description: '음악 전문 수업',
    color: '#06b6d4',
    isCompleted: false,
  },
  {
    id: 's8',
    title: '하원 준비 및 하원',
    startTime: '16:00',
    endTime: '17:00',
    date: '2026-04-07',
    description: '하원 준비 및 순차 하원',
    color: '#64748b',
    isCompleted: false,
  },
];

// ── 알림장 ──
export const MOCK_NOTICES: Notice[] = [
  {
    id: 'n1',
    type: 'common',
    title: '4월 현장학습 안내',
    content:
      '안녕하세요, 해바라기반 학부모님 😊\n\n4월 15일(수) 어린이대공원 현장학습이 예정되어 있습니다.\n준비물: 편한 옷, 운동화, 물통, 돗자리\n\n참가 동의서를 4월 10일까지 제출 부탁드립니다.\n감사합니다!',
    date: '2026-04-07',
    isRead: false,
    isSent: true,
  },
  {
    id: 'n2',
    type: 'common',
    title: '이번 주 식단 안내',
    content:
      '이번 주 식단표를 공유드립니다.\n\n월: 소불고기, 미역국\n화: 돈까스, 된장국\n수: 치킨카레, 유부장국\n목: 제육볶음, 달걀국\n금: 생선구이, 팽이버섯국\n\n알레르기 유의사항은 별도 안내드리겠습니다.',
    date: '2026-04-06',
    isRead: true,
    isSent: true,
  },
  {
    id: 'n3',
    type: 'individual',
    childId: 'c1',
    childName: '김민준',
    title: '오늘의 하루',
    content:
      '민준이가 오늘 식사 시간에 평소보다 조금 적게 먹었지만, 이후 놀이 시간에는 친구들에게 먼저 양보하며 아주 즐겁게 보냈답니다! 블록 놀이에서 멋진 성을 만들어 친구들의 박수를 받았어요 👏',
    date: '2026-04-07',
    isRead: false,
    isSent: false,
    keywords: ['식사', '양보', '블록놀이'],
    cushionLevel: 'medium',
  },
  {
    id: 'n4',
    type: 'individual',
    childId: 'c3',
    childName: '박지호',
    title: '오늘의 하루',
    content:
      '지호가 오늘 야외 활동에서 새로운 곤충을 발견하고 매우 기뻐했어요! 관찰력이 뛰어나 선생님도 감탄했답니다. 점심도 깨끗하게 다 먹었어요 😊',
    date: '2026-04-07',
    isRead: false,
    isSent: false,
    keywords: ['야외활동', '관찰력', '식사'],
    cushionLevel: 'soft',
  },
];

// ── 관찰일지 ──
export const MOCK_OBSERVATIONS: ObservationLog[] = [
  {
    id: 'obs1',
    childId: 'c1',
    childName: '김민준',
    date: '2026-04-07',
    categories: [
      {
        name: '사회관계',
        analysis: '또래와 협력하여 블록 쌓기 놀이를 진행하며, 차례를 기다리는 모습이 관찰됨.',
      },
      {
        name: '신체운동',
        analysis: '대근육 활동 시 균형 감각이 발달하고 있으며, 점프 동작이 안정적으로 수행됨.',
      },
    ],
    content:
      '민준이는 자유놀이 시간에 블록 영역에서 친구 2명과 함께 성을 만들었습니다. 블록을 나누어 쓰며 "네가 이거 해" 라고 역할을 분배하는 모습이 관찰되었습니다.',
    isAIGenerated: true,
  },
  {
    id: 'obs2',
    childId: 'c3',
    childName: '박지호',
    date: '2026-04-06',
    categories: [
      {
        name: '자연탐구',
        analysis: '숲 체험에서 다양한 곤충을 관찰하며 호기심을 표현함.',
      },
    ],
    content: '지호는 야외 숲 체험 시간에 나뭇잎 아래의 벌레를 발견하고 친구들에게 알려주었습니다.',
    isAIGenerated: true,
  },
];

// ── 대시보드 통계 ──
export const MOCK_DASHBOARD_STATS: DashboardStats = {
  totalChildren: 20,
  presentCount: 18,
  absentCount: 2,
  noticeCompleted: 8,
  noticeTotal: 20,
  observationCompleted: 5,
  observationTotal: 20,
  medicationRequests: 1,
  allergyCount: 0,
};

// ── 활동 타임라인 ──
export const MOCK_ACTIVITY_TIMELINE: ActivityTimeline[] = [
  {
    id: 'act1',
    type: 'attendance',
    title: '등원 완료',
    description: '김민준 등원 (09:05)',
    time: '09:05',
    icon: 'user-check',
  },
  {
    id: 'act2',
    type: 'attendance',
    title: '등원 완료',
    description: '이서아 등원 (09:08)',
    time: '09:08',
    icon: 'user-check',
  },
  {
    id: 'act3',
    type: 'meal',
    title: '오전 간식',
    description: '오전 간식 배식 완료',
    time: '09:30',
    icon: 'utensils',
  },
  {
    id: 'act4',
    type: 'notice',
    title: '공통 알림장 발송',
    description: '4월 현장학습 안내 발송 완료',
    time: '10:00',
    icon: 'send',
  },
  {
    id: 'act5',
    type: 'observation',
    title: '관찰일지 작성',
    description: '김민준 관찰일지 AI 생성 완료',
    time: '10:30',
    icon: 'file-text',
  },
  {
    id: 'act6',
    type: 'schedule',
    title: '다음 일정',
    description: '야외 활동 (숲 체험) 예정',
    time: '11:00',
    icon: 'calendar',
  },
];

// ── 식단 ──
export const MOCK_MEAL_PLANS: MealPlan[] = [
  {
    id: 'meal1',
    date: '2026-04-07',
    mealType: 'snack_am',
    menu: ['우유', '식빵', '딸기잼'],
    allergyWarnings: [
      {
        childId: 'c1',
        childName: '김민준',
        allergen: '우유',
        menuItem: '우유',
      },
      {
        childId: 'c7',
        childName: '한도윤',
        allergen: '밀가루',
        menuItem: '식빵',
      },
    ],
  },
  {
    id: 'meal2',
    date: '2026-04-07',
    mealType: 'lunch',
    menu: ['돈까스', '된장국', '깍두기', '쌀밥'],
    allergyWarnings: [
      {
        childId: 'c4',
        childName: '최하은',
        allergen: '계란',
        menuItem: '돈까스',
      },
      {
        childId: 'c7',
        childName: '한도윤',
        allergen: '밀가루',
        menuItem: '돈까스',
      },
    ],
  },
  {
    id: 'meal3',
    date: '2026-04-07',
    mealType: 'snack_pm',
    menu: ['떡볶이', '어묵국'],
    allergyWarnings: [
      {
        childId: 'c7',
        childName: '한도윤',
        allergen: '밀가루',
        menuItem: '떡볶이',
      },
    ],
  },
];

// ── 알림장 키워드 옵션 ──
export const NOTICE_KEYWORDS = [
  '식사',
  '수면',
  '놀이',
  '사회성',
  '언어발달',
  '배변',
  '기분/정서',
  '체육활동',
  '미술활동',
  '음악활동',
  '야외활동',
  '독서',
  '양보',
  '협동',
  '창의성',
  '집중력',
  '인사',
  '정리정돈',
];

// ── 쿠션어 레벨 설명 ──
export const CUSHION_LEVELS = [
  { value: 'soft' as const, label: '부드럽게', emoji: '🌸', description: '최대한 긍정적으로 표현' },
  { value: 'medium' as const, label: '보통', emoji: '🌿', description: '적절한 균형' },
  { value: 'strong' as const, label: '솔직하게', emoji: '💪', description: '상황을 명확하게 전달' },
];
